# Generated by Django 2.2.12 on 2023-02-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matakuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaMk', models.CharField(max_length=50)),
                ('namaDsn', models.CharField(max_length=50)),
            ],
        ),
    ]
