# Generated by Django 2.2.12 on 2023-02-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0002_matakuliah'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruangan',
            name='matakuliah_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.Matakuliah'),
        ),
    ]
