# Generated by Django 2.2.12 on 2023-02-28 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0003_ruangan_matakuliah_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matakuliah',
            old_name='namaDsn',
            new_name='Dosen',
        ),
        migrations.RenameField(
            model_name='matakuliah',
            old_name='namaMk',
            new_name='Matakuliah',
        ),
        migrations.RenameField(
            model_name='ruangan',
            old_name='nama',
            new_name='Lab',
        ),
    ]
