# Generated by Django 2.2.12 on 2023-02-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0005_auto_20230228_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruangan',
            name='keterangan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
