# Generated by Django 2.2.12 on 2023-02-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0006_ruangan_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='durasi',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='tanggal',
            field=models.DateTimeField(null=True),
        ),
    ]
