# Generated by Django 2.2.12 on 2023-02-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0007_auto_20230228_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('notelp', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='matakuliah',
            name='dosen',
        ),
        migrations.RemoveField(
            model_name='matakuliah',
            name='durasi',
        ),
        migrations.RemoveField(
            model_name='matakuliah',
            name='lab_id',
        ),
        migrations.RemoveField(
            model_name='matakuliah',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='sks',
            field=models.IntegerField(null=True),
        ),
    ]
