# Generated by Django 2.2.12 on 2023-02-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0009_jadwal'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='waktu',
            field=models.TimeField(null=True),
        ),
    ]
