# Generated by Django 2.2.12 on 2023-02-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0010_jadwal_waktu'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='dosen_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.Dosen'),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='lab_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.Ruangan'),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='matakuliah_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.Matakuliah'),
        ),
    ]
