# Generated by Django 2.2.12 on 2023-03-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0011_auto_20230228_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='hari',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
