# Generated by Django 2.2.12 on 2023-03-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0013_dosen_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
