# Generated by Django 2.2.12 on 2023-03-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0014_auto_20230301_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='notelp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
