# Generated by Django 2.2.12 on 2023-03-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0015_auto_20230301_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruangan',
            name='keterangan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
