# Generated by Django 2.2.12 on 2023-03-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0016_auto_20230301_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruangan',
            name='lab',
            field=models.IntegerField(max_length=50),
        ),
    ]
