# Generated by Django 2.2.12 on 2023-03-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0018_auto_20230302_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='hari',
        ),
    ]
