# Generated by Django 2.2.12 on 2023-03-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0019_remove_jadwal_hari'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='nip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
