# Generated by Django 2.2.12 on 2023-03-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0020_dosen_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='notelp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
