# Generated by Django 2.2.12 on 2023-03-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0021_auto_20230303_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='nip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='notelp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
