# Generated by Django 2.2.12 on 2023-03-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0023_auto_20230303_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matakuliah',
            old_name='matakuliah',
            new_name='matkul',
        ),
    ]
