# Generated by Django 2.2.12 on 2023-03-04 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0024_auto_20230303_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='matakuliah_id',
        ),
        migrations.AddField(
            model_name='jadwal',
            name='matkul_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.Matakuliah'),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='kodematkul',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
