# Generated by Django 2.2.12 on 2023-03-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0025_auto_20230304_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='jadwal',
            name='hari',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
