# Generated by Django 2.2.12 on 2023-04-11 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0026_auto_20230309_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tempat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelompok_kelas', models.CharField(max_length=2, null=True)),
                ('jadwal_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.Jadwal')),
                ('ruangan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.Ruangan')),
            ],
        ),
    ]
