# Generated by Django 4.2.1 on 2023-05-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0027_tempat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='nip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='notelp',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
